package com.prodbuddy.observation;

import net.sourceforge.plantuml.SourceStringReader;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;

/**
 * Native Java renderer using PlantUML.
 */
public final class LocalDiagramRenderer {

    /** Max events. */
    private static final int MAX_EVENTS = 50;
    /** Max sender length. */
    private static final int MAX_SENDER = 30;
    /** Max method length. */
    private static final int MAX_METHOD = 50;
    /** Max action length. */
    private static final int MAX_ACTION = 100;
    /** Truncation suffix. */
    private static final int TRUNC_SUFFIX = 3;

    /**
     * Renders a list of events to a PNG.
     * @param events The events to render
     * @return PNG bytes
     * @throws IOException if rendering fails
     */
    public byte[] renderSequence(final List<ObservationEvent> events)
            throws IOException {
        if (events == null || events.isEmpty()) {
            return new byte[0];
        }

        List<ObservationEvent> limited = events.size() > MAX_EVENTS
                ? events.subList(events.size() - MAX_EVENTS, events.size())
                : events;

        String plantUml = buildPlantUml(limited);

        SourceStringReader reader = new SourceStringReader(plantUml);
        try (ByteArrayOutputStream os = new ByteArrayOutputStream()) {
            reader.generateImage(os);
            return os.toByteArray();
        }
    }

    private String buildPlantUml(final List<ObservationEvent> limited) {
        StringBuilder sb = new StringBuilder();
        sb.append("@startuml\n");
        appendSkinParams(sb);
        
        sb.append("header ProdBuddy High-Fidelity Tracing\n");
        sb.append("title System Sequence Trace\n");
        sb.append("footer Generated by ProdBuddy Observation Engine\n");
        
        sb.append("autonumber\n");

        for (ObservationEvent event : limited) {
            appendStyledEvent(sb, event);
        }

        sb.append("@enduml");
        return sb.toString();
    }

    private void appendSkinParams(final StringBuilder sb) {
        sb.append("!theme plain\n");
        sb.append("skinparam style strictuml\n");
        sb.append("skinparam roundcorner 15\n");
        sb.append("skinparam ParticipantPadding 20\n");
        sb.append("skinparam BoxPadding 10\n");
        sb.append("skinparam MaxMessageSize 300\n");
        sb.append("skinparam SequenceLifeLineBorderColor #AAAAAA\n");
        sb.append("skinparam SequenceLifeLineBackgroundColor #F5F5F5\n");
        sb.append("skinparam ParticipantBorderColor #CCCCCC\n");
        sb.append("skinparam ParticipantBackgroundColor #FFFFFF\n");
        sb.append("skinparam NoteBackgroundColor #FFFDE7\n");
        sb.append("skinparam NoteBorderColor #FBC02D\n");
        sb.append("skinparam ArrowColor #333333\n");
        sb.append("skinparam DefaultFontName \"Verdana\"\n");
        sb.append("skinparam DefaultFontSize 12\n");
    }

    private void appendStyledEvent(final StringBuilder sb,
                                   final ObservationEvent event) {
        String sId = event.getSender();
        String rId = event.getReceiver();
        String sDisp = getDisplayName(sId, event.getMetadata());
        String rDisp = getDisplayName(rId, event.getMetadata());

        String s = "\"" + sDisp + "\"";
        String r = "\"" + rDisp + "\"";
        String m = sanitize(event.getMethod(), MAX_METHOD);
        String a = sanitize(event.getAction(), MAX_ACTION);

        applyColors(sb, sId, sDisp, event.getMetadata());
        applyColors(sb, rId, rDisp, event.getMetadata());

        appendNoteIfPresent(sb, s, m, event.getMetadata());

        String arrow = getArrowType(m, a);
        sb.append(s).append(arrow).append(r).append(" : ").append(m);
        if (a != null && !a.isEmpty()) {
            sb.append("\\n(").append(a).append(")");
        }
        sb.append("\n");
    }

    private void appendNoteIfPresent(final StringBuilder sb, final String s,
                                     final String m,
                                     final java.util.Map<String, String> meta) {
        String nColor = meta.get("noteColor");
        if (nColor != null) {
            String noteText = meta.getOrDefault("noteText", m);
            String wrapped = wrap(noteText, 80);
            sb.append("note over ").append(s).append(" ")
              .append(nColor).append("\n");
            sb.append("  ").append(wrapped).append("\n");
            sb.append("end note\n");
        }
    }

    private String wrap(final String text, final int width) {
        if (text == null || text.length() <= width) {
            return text;
        }
        StringBuilder sb = new StringBuilder();
        int lastSpace = -1;
        int lineStart = 0;
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            if (c == ' ') {
                lastSpace = i;
            } else if (c == '\n') {
                lineStart = i + 1;
                lastSpace = -1;
            }
            if (i - lineStart >= width) {
                if (lastSpace != -1) {
                    sb.append(text, lineStart, lastSpace).append("\n");
                    lineStart = lastSpace + 1;
                    lastSpace = -1;
                } else {
                    sb.append(text, lineStart, i).append("\n");
                    lineStart = i;
                }
            }
        }
        sb.append(text.substring(lineStart));
        return sb.toString();
    }

    private String getArrowType(final String m, final String a) {
        String lowerM = m.toLowerCase();
        String lowerA = a.toLowerCase();
        
        if (lowerA.contains("error") || lowerA.contains("failed") 
                || (lowerA.startsWith("http ") && !lowerA.startsWith("http 2"))) {
            return " -[#red]> ";
        }
        
        if (lowerM.contains("response") || lowerM.contains("result") 
                || lowerA.contains("success") || lowerA.contains("failed")) {
            return " --> ";
        }
        
        return " -> ";
    }

    private String getDisplayName(final String actorId,
                                  final java.util.Map<String, String> meta) {
        String styledActor = meta.get("styledActor");
        if (actorId.equals(styledActor)) {
            String disp = meta.get("displayName");
            if (disp != null) {
                return disp;
            }
        }
        return getDefaultDisplayName(actorId);
    }

    private String getDefaultDisplayName(final String id) {
        ObservationStyling.Styling s = ObservationStyling.get(id);
        if (s != null) {
            return s.getDisplayName();
        }
        return id;
    }

    private void applyColors(final StringBuilder sb, final String actorId,
                             final String displayName,
                             final java.util.Map<String, String> meta) {
        String styledActor = meta.get("styledActor");
        if (!actorId.equals(styledActor)) {
            return;
        }

        String sColor = meta.get("actorColor");
        if (sColor == null) {
            ObservationStyling.Styling s = ObservationStyling.get(actorId);
            if (s != null) {
                sColor = s.getColor();
            }
        }

        if (sColor != null && !sColor.isEmpty()) {
            sb.append("participant \"").append(displayName)
              .append("\" ").append(sColor).append("\n");
        }
    }

    private String sanitize(final String text, final int maxLength) {
        if (text == null) {
            return "unknown";
        }

        String cleaned = text.replace("\n", " ")
                             .replace("\r", "")
                             .trim();

        if (cleaned.length() > maxLength) {
            return cleaned.substring(0, maxLength - TRUNC_SUFFIX) + "...";
        }
        return cleaned;
    }
}
